#PCA (Principal Component Analysis):


1.PCA (Principal Component Analysis) is a technique in Machine Learning and Data Science that reduces the number of features while keeping as much important information as possible.

2.By projecting a high-dimensional dataset into a smaller feature space, PCA also minimizes, or altogether eliminates, common issues such as multicollinearity and overfitting. Multicollinearity occurs when two or more independent variables are highly correlated with one another, which can be problematic for causal modeling. Overfit models will generalize poorly to new data,

3.PCA is a dimension reduction technique like linear discriminant analysis (LDA). In contrast to LDA, PCA is not limited to supervised learning tasks. For unsupervised learning tasks, this means PCA can reduce dimensions without having to consider class labels or categories.

4.PCA and k-means clustering are both unsupervised machine learning techniques used for data analysis, but they have different goals and methods. PCA is used to reduce the dimensionality of the data, while k-means clustering groups data points together based on similarity. The technique you select depends on the specific dataset and goals of your analysis.

5.PCA creates new variables, such as principal components, that are linear combinations of the original variables.

#Calculating principal components1. Scaling (Standardization)

1. Convert all features to same scale (mean = 0, variance = 1)

2. Compute Covariance Matrix
   Measure how features vary and relate to each other

3. Calculate Eigenvalues & Eigenvectors
   Eigenvalues → importance (variance)
   Eigenvectors → directions (principal components)

4. Select Top Components
   Choose top eigenvalues that explain required variance (e.g., 90–95%)

5. Transform Data
   Multiply original data with selected eigenvectors to get principal components

In [25]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
columns = [
    "id", "diagnosis",
    "radius_mean", "texture_mean", "perimeter_mean", "area_mean", "smoothness_mean",
    "compactness_mean", "concavity_mean", "concave_points_mean", "symmetry_mean", "fractal_dimension_mean",

    "radius_se", "texture_se", "perimeter_se", "area_se", "smoothness_se",
    "compactness_se", "concavity_se", "concave_points_se", "symmetry_se", "fractal_dimension_se",

    "radius_worst", "texture_worst", "perimeter_worst", "area_worst", "smoothness_worst",
    "compactness_worst", "concavity_worst", "concave_points_worst", "symmetry_worst", "fractal_dimension_worst"
]

In [5]:
df= pd.read_csv('/content/wdbc.data',names=columns)

In [6]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [24]:
df.shape

(569, 31)

In [7]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave_points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave_points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave_points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave_points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave_points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave_points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

In [11]:
df['diagnosis'].value_counts(normalize=True)

diagnosis
B    0.627417
M    0.372583
Name: proportion, dtype: float64

In [17]:
df.isnull().any().sum()

np.int64(0)

In [16]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.drop('id', axis=1,inplace=True)

In [20]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [21]:
x=df.drop('diagnosis',axis=1)
y=df['diagnosis']

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(455, 30) (455,)
(114, 30) (114,)

#Random Forest before scaling the data

In [88]:
rf_before= RandomForestClassifier(n_estimators=100,random_state=42)

In [26]:
scaler= StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [27]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()
lg.fit(x_train_scaled,y_train)

LogisticRegression()

In [28]:
y_predict=lg.predict(x_test_scaled)

In [29]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [30]:
accuracy_score(y_test,y_predict)

0.9736842105263158

In [31]:
confusion_matrix(y_test,y_predict)

array([[70,  1],
       [ 2, 41]])

In [32]:
from sklearn.decomposition import PCA
pca= PCA(n_components=0.95)

In [33]:
x_train_pca=pca.fit_transform(x_train_scaled)
x_test_pca=pca.transform(x_test_scaled)

In [34]:
print(x_train_pca.shape,x_test_pca.shape)

(455, 10) (114, 10)

In [35]:
pca.explained_variance_ratio_

array([0.43502782, 0.19500007, 0.09781519, 0.06486409, 0.05253378,
       0.041128  , 0.0223559 , 0.01647952, 0.01380052, 0.01205262])

In [36]:
lg.fit(x_train_pca,y_train)

LogisticRegression()

In [37]:
y=predict=lg.predict(x_test_pca)

In [38]:
accuracy_score(y_test,y)

0.9824561403508771

In [39]:
confusion_matrix(y_test,y)

array([[70,  1],
       [ 1, 42]])

In [86]:
classification_report(y_test,y)

'              precision    recall  f1-score   support\n\n           B       0.99      0.99      0.99        71\n           M       0.98      0.98      0.98        43\n\n    accuracy                           0.98       114\n   macro avg       0.98      0.98      0.98       114\nweighted avg       0.98      0.98      0.98       114\n'

#Desicion Tree

In [40]:
from sklearn.tree import DecisionTreeClassifier

In [41]:
dc=DecisionTreeClassifier(criterion='gini',max_depth=3,random_state=0)

In [42]:
dc.fit(x_train_pca,y_train)

DecisionTreeClassifier(max_depth=3, random_state=0)

In [43]:
y_predict_dc=dc.predict(x_test_pca)

In [44]:
accuracy_score(y_test,y_predict_dc)

0.956140350877193

In [45]:
confusion_matrix(y_test,y_predict_dc)

array([[68,  3],
       [ 2, 41]])

#Random Forest

In [46]:
from sklearn.ensemble import RandomForestClassifier

In [47]:
rf=RandomForestClassifier()

In [48]:
rf.fit(x_train_pca,y_train)

RandomForestClassifier()

In [49]:
y_test_random=rf.predict(x_test_pca)

In [50]:
accuracy_score(y_test,y_test_random)

0.9473684210526315

In [51]:
confusion_matrix(y_test,y_test_random)

array([[68,  3],
       [ 3, 40]])

In [52]:
rf=RandomForestClassifier(max_depth=3, random_state=42,)

In [53]:
rf.fit(x_train_pca,y_train)

RandomForestClassifier(max_depth=3, random_state=42)

In [54]:
y_test_random2=rf.predict(x_test_pca)

In [55]:
accuracy_score(y_test,y_test_random2)

0.9298245614035088

In [56]:
confusion_matrix(y_test,y_test_random2)

array([[68,  3],
       [ 5, 38]])

In [76]:
rf = RandomForestClassifier(max_depth=9,n_estimators=180, random_state=42)

In [77]:
rf=rf.fit(x_train_pca,y_train)

In [78]:
y_test_random3=rf.predict(x_test_pca)

In [79]:
accuracy_score(y_test,y_test_random3)

0.9473684210526315

In [80]:
confusion_matrix(y_test,y_test_random3)

array([[68,  3],
       [ 3, 40]])

In [82]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5, 7, None],
    'criterion': ['gini', 'entropy']
}

rf = RandomForestClassifier(random_state=42)

grid = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5)

grid.fit(x_train_pca, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 5, 7, None],
                         'n_estimators': [100, 200]})

In [83]:
y_predict_grid=grid.predict(x_test_pca)

In [84]:
accuracy_score(y_test,y_predict_grid)

0.9473684210526315

In [85]:
confusion_matrix(y_test,y_predict_grid)

array([[68,  3],
       [ 3, 40]])